### PR TITLE
Added Variables for Prefill Email and Computer Name

### PR DESCRIPTION
**Pull request by AndrewMBarnett**
- Added variable fields for true or false in the prefill sections for email and computer name for the Welcome screen
- Added email ending variable for custom email endings in your environment

### CODE REVIEW

**Comment by dan-snelson** [comment]
Thanks for the PR, @AndrewMBarnett.

_If_ this does merged, it'd be included in version `1.15.0`.

I just changed the base branch and now there are conflicts; please review.

**Comment by AndrewMBarnett** [comment]
Hi @dan-snelson.

For the conflicts, are you wanting me to add my changes to the files listed with conflicts? Just want to make sure I resolve the correct conflicts.

**Comment by dan-snelson** [comment]
Sorry for any Dan-induced confusion, Andrew; please just add your changes to `Setup-Your-Mac-via-Dialog.bash`.

**Comment by AndrewMBarnett** [comment]
Hey Dan, I don't know if I have access to add anything? 

Is this what you are looking for or are do you want the actual script edits?

#   Version 1.15.0, 02-Apr-2024
#   - Added variables for prefill Email and Computer Name Fields for the Welcome dialog screen (thanks, @AndrewMBarnett)[Pull Request No. 145](https://github.com/setup-your-mac/Setup-Your-Mac/pull/145)
#

**Comment by dan-snelson** [comment]
Greetings, @AndrewMBarnett!

Will you please pull the `1.15.0` branch a re-re-submit only `Setup-Your-Mac-via-Dialog.bash` **one last time** ?

(If it still doesn't behave, I can manually add your changes, but I'm not enough of a `git` Ninja-Jedi to give you the deserved credit.)

Thanks.

**Comment by dan-snelson** [comment]
@AndrewMBarnett:

Your changes have been included in [`1.15.0-b12`](https://github.com/setup-your-mac/Setup-Your-Mac/blob/1.15.0/Setup-Your-Mac-via-Dialog.bash).

Thanks.

**Pull request closed without merging**
